DWAPlannerROS:
  max_vel_x: 0.7
  min_vel_x: 0.1
  max_rotational_vel: 1.1
  min_in_place_rotational_vel: 0.4
  
  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  # Dynamic Window Parameters
  # Dynamic Window Parameters
  sim_time: 1.5                   # Increased simulation time for better trajectory evaluation
  vx_samples: 10                  # More samples for finer control
  vtheta_samples: 40              # More samples for finer control
  path_distance_bias: 50.0        # Increased to prioritize following the path
  goal_distance_bias: 25.0        # Increased to prioritize reaching the goal
  occdist_scale: 0.05             # Decreased to make robot more sensitive to obstacles
  forward_point_distance: 0.325

  # Trajectory scoring
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  oscillation_reset_dist: 0.05
